### ISSUE TITLE
First post ad overlaps

### ISSUE THREAD

**Issue by ReyKoxha** [NodeBB-Community/nodebb-plugin-adsense#1]
If the first post ad is in use, it will overlap the second post slightly.
On mobile the ad will underlap the second post.

Fix:

```
            if (url.url.substring(0, 6) == "topic/") {
                if(data.after_first_post_id){
                    $(".posts >li:first-child").after("<li>" + getInsCode(data.client_id, data.after_first_post_id, '', 'margin: 15px auto', 'auto') + "</li><br>");
                    (adsbygoogle = window.adsbygoogle || []).push({});
                }
            }
```

**Comment by barisusakli** [comment]
I think this only happens if you pick a non-responsive ad unit.

**Comment by ReyKoxha** [comment]
False. It happens **when** you use a responsive ad unit.

**Comment by ReyKoxha** [comment]
Just wanting to add a similar behaviour to this.
The first post ad (not the one after it) does not gets displayed properly.
Instead a white space remains on the right side, causing the ad to show up only 3/4.
