### ISSUE TITLE
Feature request: Disable ads for logged in users.

### ISSUE THREAD

**Issue by Jenkler** [NodeBB-Community/nodebb-plugin-adsense#10]
Is it possible to fix so that ads will be disabled for some cases.

Whould be nice with some settings.
- No ads for admins
- Logged in users
- Ad free group, if member is a member of group XXX = no ads. and so on

Best to start with no ads for logged in users maybe ;) Feel free to mess me if this is something you thing is good :)

**Comment by barisusakli** [comment]
ads can be disabled for certain groups now
