### ISSUE TITLE
Settings not opening in ACP

### ISSUE THREAD

**Issue by Nonotrynick** [NodeBB-Community/nodebb-plugin-adsense#18]
The version 1.19.2 and 2.5.8 have the same error. When I try to open the plugin page, it does not open.

No error message appears. The page is not loading.

**Comment by Nonotrynick** [comment]
I tried rebuild

**Comment by barisusakli** [comment]
Try with 2.0.0 or 3.0.0 and let me know if you get any errors in the browser console.
