### ISSUE TITLE
hide by category numbers

### ISSUE THREAD

**Issue by Nonotrynick** [NodeBB-Community/nodebb-plugin-adsense#19]
Is there a feature to hide ads in certain categories such as html extend?

**Comment by barisusakli** [comment]
You can do this by using a html widget. Create one like below and replace the values with your pub-id and slot id.

![image](https://github.com/NodeBB-Community/nodebb-plugin-adsense/assets/2583394/3ffd2c9f-d4bb-41ee-b12c-fb59975433f6)


Then add the script for adsense into head section in acp like below, again replace your pub-id with the correct one.

![image](https://github.com/NodeBB-Community/nodebb-plugin-adsense/assets/2583394/453d08ea-9fa9-4f0d-8fb7-15a4e8b8096d)

Then you can control which categories it shows on.
