### ISSUE TITLE
No "Google Adsense" menu item after activation

### ISSUE THREAD

**Issue by ww9rivers** [NodeBB-Community/nodebb-plugin-adsense#20]
The README says, _After activating plugin, you will see a reference in admin panel left menu called "Google Adsense"_. However, I installed the version 4.0.0 of this plugin in a NodeBB 3.4.3 site, I am not able to find the the _Google Adsense_ menu item.

Not sure if the theme matters in this case. I am using Persona theme.

**Comment by ww9rivers** [comment]
Not sure what happened. The "Google Adsense" menu item showed up between my opening the issue and now.

**Comment by barisusakli** [comment]
I updated the readme, you need to activate plugin and then rebuild the assets either via the ACP or with `./nodebb build` form the CLI
