### ISSUE TITLE
first post ad margin problem (mobile)

### ISSUE THREAD

**Issue by aribuga** [NodeBB-Community/nodebb-plugin-adsense#3]
It turns over the content.

![adproblem](https://cloud.githubusercontent.com/assets/15672497/12139431/341f4724-b469-11e5-9864-8bb2328ed068.jpg)

**Comment by ReyKoxha** [comment]
Duplicate. See this:
https://github.com/NodeBB-Community/nodebb-plugin-adsense/issues/1
