### ISSUE TITLE
Is it compatible with 0.9.4?

### ISSUE THREAD

**Issue by Nisthar** [NodeBB-Community/nodebb-plugin-adsense#9]
I enabled nodebb-plugin-adsense. But i can't find the plugin in the plugin section (section where i can download/install plugin). Also even after removing the plugin, I can't find the plugin in the download section. Isn't it compatible with 0.9.4 version?

**Comment by aribuga** [comment]
`git clone https://github.com/NodeBB-Community/nodebb-plugin-adsense.git`

**Comment by yariplus** [comment]
It should be on the downloads page. How did you enable it if you can't find it in the downloads page?

I installed it on 0.9.4 from the downloads page and it seems to work fine. Perhaps something else went wrong. Maybe try resetting it from the command line `./nodebb reset -p nodebb-plugin-adsense`

**Comment by Nisthar** [comment]
I was able to see it in the download section. But i didn't set the plugin settings for 2 or 3 days. Now its giving a blank page when i click on it and its not appearing in the plugins section.

**Comment by Nisthar** [comment]
I removed it using `./nodebb reset nodebb-plugin-adsense` and `npm remove nodebb-plugin-adsense`

**Comment by yariplus** [comment]
idk, make sure the directory `/nodebb/node_modules/nodebb-plugin-adsense` is actually removed. `npm remove` won't remove git repos. Also, make sure you are using the `-p` flag on your reset command. `./nodebb reset -p nodebb-plugin-adsense` Try cloning it in the `/nodebb/node_modules` directory if it still doesn't work, as @pikshub says.

**Comment by Nisthar** [comment]
@yariplus Yes. I did used the -p flag. I'll check if there is a folder in npm modules.

**Comment by Nisthar** [comment]
@yariplus Yes. There is nodebb-plugin-adsense folder in node_modules folder

**Comment by Nisthar** [comment]
@yariplus BTW could you provide more info on how to install it using git clone. Do i need to stop nodebb before adding it. Because, I am hosting my app on openshift and had a lot of issues for small mistakes.

**Comment by yariplus** [comment]
Go to your local `/nodebb/node_modules` folder, delete the `nodebb-plugin-adsense` folder. Run `git clone https://github.com/NodeBB-Community/nodebb-plugin-adsense.git` Push the changes to your app.

**Comment by Nisthar** [comment]
@yariplus I want to run git clone in the node_modules directory.  Right?

**Comment by Nisthar** [comment]
Ok. Ran it in node_modules folder. Let me check if i can run it.

**Comment by Nisthar** [comment]
Still the same. Can't find the plugin after reloading the nodebb app 
http://i.imgur.com/pvo4uzl.jpg

**Comment by Nisthar** [comment]
@barisusakli Any updates?

**Comment by barisusakli** [comment]
This plugin should be compatible with 1.0.0 it just needs to be republished to npm with a correct compat string. I will publish it tomorrow.

Why is your installed plugins list empty? It should at least have the default plugins there.

**Comment by Nisthar** [comment]
@barisusakli Yes. It has the default plugins there. But i can't find the adsense plugin in the downloadable list even after uninstalling. I uninstalled manually with the commands `./nodebb reset -p nodebb-plugin-adsense` and `npm remove nodebb-plugin-adsense`. At first, I was able to see the plugin and download it, But i don't know what went wrong.

This plugin is a must for nodebb applications. Waiting for the fix.

**Comment by yariplus** [comment]
Not an expert on openshift, but is the problem possibly that the `.gitignore` file is not pushing the node_modules folder to your app?

**Comment by Nisthar** [comment]
@yariplus No, I have all the plugins like `composer-default` and other third-party plugins like `imgur`, etc. I also had adsense in the downloadable list. I downloaded it, left it untouched for 2 or 3 days. Now when i tried to access the acp page, It give me a blank white page with title `Google Adsense`. I tried to uninstall it from the admin page. But i was not able to find it in the installed plugins list.

I thought it may be due to recent changes in nodebb or the plugin.

**Comment by barisusakli** [comment]
I published the 1.0.0 compatible version to npm now.

**Comment by Nisthar** [comment]
@barisusakli Wow. Thanks :+1: 

Can i find it in the acp downloadable plugin section?

**Comment by barisusakli** [comment]
It should show up in about an hour.

**Comment by Nisthar** [comment]
Thanks. Will post here my results.

**Comment by Nisthar** [comment]
@barisusakli Sorry, I can't see it under the download plugin section.

I tried `git clone https://github.com/NodeBB-Community/nodebb-plugin-adsense.git` But I can't get the plugin to show in my ACP.

**Comment by Nisthar** [comment]
@barisusakli Ok. I can see it in 1.x.x version. But not in 0.9.4 version.

**Comment by Nisthar** [comment]
@barisusakli Its working in my localhost version of 1.0.0. But not in 0.9.4 version.

**Comment by Nisthar** [comment]
I am new to nodebb plugin development. But i see the id of the plugin is different from the id in package.json.
